with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "mocks/{{.PackagePath}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
    go-todos-api/repositories:
        interfaces:            
            TodoRepository: